### ISSUE TITLE
`mapping_code_{sp}` and `streams_{sp}` symbology for resident species when `HYDRO` (dams) are involved

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/dff-2022#127]
For areas like the `KOTL` watershed group, all streams are above dams.  We deal with "resident" fish populations so still need to have map symbology that helps us understand connectivity in the watershed group.

In the current symbology specs for the `bcfishpass` `qlr` `DAM` is involved.  Guessing this is meant to be `HYDRO`....  @smnorris - is the `DAM` in the symbology of the `streams` layer meant to be `HYDRO` ? Is this issue already dealt with somehow for places like the `ELKR` watershed group - https://github.com/smnorris/bcfishpass/issues/110 ?

Editing the `qgs` project file or a layer specific `qlm` to swap out `DAM` for `HYDRO` in the `mapping_code_{sp}` columns of the `bcfishpass.streams` layer for `resident` species of interest such as `bt` and `wct` allows us to see symbology but shows everything upstream of the dams as blocked so does not symbolize connectivity above the dams (see screenshots below).  Potential path forward?:

- Modify the `streams_{sp}` layers for `resident` species of interest so when a `DAM` is involved for `bt`, `wct`(rainbow too soon hopefully) the stream still shows as orange (like `MODELLED`). Save the `qlm` as a `streams_above_dams` or something like that and then apply to specific `streams_{sp}` layers in Q?

will load example project to Q and share for collaboration in case that is helpful

![image](https://github.com/NewGraphEnvironment/dff-2022/assets/46538103/be2bd3c2-df08-45cb-9a4b-131e33af3d0e)

![image](https://github.com/NewGraphEnvironment/dff-2022/assets/46538103/486949f4-03ac-4cd4-bc14-bec71dabaf0d)

Before editing `qgs` file
![image](https://github.com/NewGraphEnvironment/dff-2022/assets/46538103/3c70da77-34b4-4aa0-9f76-3fc5477d2054)

After editing `qgs` file to swap `DAM` for `HYDRO`
![image](https://github.com/NewGraphEnvironment/dff-2022/assets/46538103/abd3082c-da32-44cb-8d72-f3940eb43f37)

After editing symbology to swap orange for red when `HYDRO` involved

![image](https://github.com/NewGraphEnvironment/dff-2022/assets/46538103/036588ff-d555-493f-aa2f-c8bbbb23f469)

**Comment by smnorris** [comment]
Yes - focus has been on salmon/steelhead, mapping of resident spp behind dams need to be resolved.

**Comment by smnorris** [comment]
open issue in bcfishpass is here https://github.com/smnorris/bcfishpass/issues/304

**Comment by smnorris** [comment]
Yes, agree everything upstream of dams for resident species should be coloured as per above modelled/potential barriers. I also think that we don't really need `HYDRO` in the mapping code, a dam is a dam in terms of symbolization for resident species. The `HYDRO` code is more for mapping of historic anadromous habitat and I'm not sure it is really needed at this point either.

**Comment by NewGraphEnvironment** [comment]
Hmmm. Maybe we’re not quite there yet with that symbolization with that adjustment. Really we want to be able to fix culverts on tribs to main rivers (Kootenay River in that example) and be able to visualize that its restored connectivity within the system… As it is there, if I have my head wrapped around it correctly,
If we don’t fix the dams we won’t be able to visualize any connectivity restoration work getting done upstream… maybe the `HYDRO` label could be useful still but perhaps it could be ignored for our use case of exploring road/stream crossing restoration opportunities…

**Comment by smnorris** [comment]
For barriers that get fixed we are already symbolizing as green. 
But for resident spp, some other colour indicating upstream of dam but not upstream of a modelled crossing would be useful.

**Comment by NewGraphEnvironment** [comment]
The concept of a HYDRO label for historic anadromous access is actual pretty awesome. There is TONS going on these days in the KOTL and LARL etc reagarding reintroductions (happening already with huge fry releases planned very soon) and modelling for salmon suitability. For those watershed groups dams in states should prob be considered too. All that is likely too much to deal with right now but perhaps the HYDRO label need not be changed - just pulled into the symbology. Just a thought…

**Comment by smnorris** [comment]
I have added a column to streams table that indicates if the *next* barrier downstream is a dam. Those streams can be given a different colour, and streams upstream of modelled crossings / PSCIS barriers retain current colour. It isn't perfect but seems better than current style and can be adjusted as we figure this out.

**Comment by smnorris** [comment]
I'll add a column indicating if a hydro dam is the next barrier downstream as well. But I'll hold off on any changes to anadromous symbology for now.
