### ISSUE TITLE
`form_fiss_site` and `form_fiss_fish`

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/dff-2022#129]
- [x] 1. remove `surveyor` fields in favor of `crew_members`

- [x] 2. remove default values from `utm_easting` and `utm_northing`, or remove fields all together. Maybe add two fields for waypoint top of site and one for waypoint bottom?

- [ ] 3. add informative aliases to fields that could use further explanation (ex: D95)

- [ ] 5. remove decimal constraint from survey site length

- [ ] 6. add photo alias for photo of site bottom and photo site top

**Comment by NewGraphEnvironment** [comment]
closing as some items are super beta fish card related and some are mature tested site card.  Can sort out in other places

**Comment by NewGraphEnvironment** [comment]
- [ ] remove `camera_id` and `gps_id` as we will assume variation from `mergin_user` would be in `comments`.  May just do in the Q form and leave removal from attribute table till later.
- [ ] remove `comments_2`.  Will wait to make sure there was not a lose of data or not enough room for `comments` to be fine before doing so. Should do in Q as well as build script when done.
