### ISSUE TITLE
Update field forms to allow easier transfer of data to provincial templates

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/dff-2022#144]
See comment in onboarding [here](https://github.com/NewGraphEnvironment/onboarding/issues/32#issuecomment-1758217019). Issues that come up during the data transfer process will be added to the list below and closed. 

- [ ] add default value of "No" to all Yes/No fields such as beaver activity, fish presence, and embedment, to avoid NULL values
- [ ] CBS numeric fields have NA values when user inputs a 0. Seen in outlet drop, outlet pool, culvert slope, and stream slope.

**Comment by NewGraphEnvironment** [comment]
closing in favour of #119 and #129 to keep all the updates from the past and future in one place and form type specific

**Comment by NewGraphEnvironment** [comment]
fiss form is is actually #148
