### ISSUE TITLE
Match fiss_site forms to hab con template

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/dff-2022#47]
- the fields for feature times are missing from the form_fiss_site_tidy (not actually necessary at time issue was closed)
- the fields "morphology", "l_bank_texture_dominant_2" and "r_bank_texture_dominant_2" are either blank or have a value of "FALSE"

**Comment by NewGraphEnvironment** [comment]
latest version of the `tidy_fiss` script is in https://github.com/NewGraphEnvironment/fish_passage_moti_2022_reporting/tree/main/scripts (currently private repo but not for long).

Noticed that the `gazetted_name` column is named `gazetted_names` in the site information page.  This causes a lack of names to come through in `form_loc`
