### ISSUE TITLE
build script to sort photos into directories and append photo name to end of photo file name

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/dff-2022#65]
upstream
downstream
inlet
outlet
barrel
road

**Comment by Mateo9569** [comment]
I'll do a trial and error on this when I get the chance. Might not even need a script. I would think you would be able to do this in the attribute forms in our Q mergin project by adding a default of sorts?

**Comment by NewGraphEnvironment** [comment]
Good idea but currently not an option I don't think because of this https://github.com/MerginMaps/input/issues/1595

potential workflow to abstract later to pull out the appended word after `photo_{word}` can be tweaked from the `0120-photos.R` scripts


1. use `case_when` to mutate `site_id` from `pscis_id` and `modelled_crossing_id`
2. run  a bunch of mutates ex. `mutate(photo_downstream_renamed = paste0(photo_downstream, '_downstream')
3. `dplyr::pivot_longer` to make a 3 column dataframe with headers `site_id`, `name_before`, `name_after`
4. `pull` `site_id` and `create.dir` for that list
5. `mutate` `name_before` and `name_after` to be full path filenames with the `site_id` installed in `name_after` of course
6. pull the name columns and run them through `fpr::fpr_photo_change_names`

**Comment by NewGraphEnvironment** [comment]
https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/issues/6

working function built in https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/blob/main/scripts/01_prep_inputs/0120-photos.R
