### ISSUE TITLE
Need to adjust `photo_resize_convert_batch` function and code in `0120-photos.R` script to convert photos and create folders

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/dff-2022#67]
I think this section for photo conversion could use a bit of reworking so that it's more reproducible, especially now that we have mergin photos too. Just a few ideas:
- Put all original photos directly into OneDrive after taking them in the field into a folder with the appropriate name of person who took photo. There should be a way to automatically backup photos to OneDrive from phone settings once you enter wifi.
- Have 4 photo folders (MW, AI, Mergin, Bute)
- Then adjust script so it targets these OneDrive folders, then converts sizes

**Comment by NewGraphEnvironment** [comment]
hmm. Think it is best to close this one in favour of #65 ;)
