### ISSUE TITLE
convert column names to lower case when writing layers using `bcdata dump` to `geojson` then to `gpkg` with `ogr2ogr`

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/dff-2022#70]
this looks like a very promising start.  Particularly if we can capture the `ogrinfo` regarding all the column names and assign as variable

https://gist.github.com/capooti/f1f272eeefc1ceb89007

**Comment by NewGraphEnvironment** [comment]
looks like `bc2pg` does it here with python https://github.com/NewGraphEnvironment/bcdata/blob/e818f42fa25b82340d6c97fbdc860c12bb27c170/bcdata/bc2pg.py#L96

**Comment by smnorris** [comment]
Yes. 
And I think it would be a reasonable option (or even default) to add to `bcdata.get_data()` etc. 
The upper case columns are annoying.

**Comment by NewGraphEnvironment** [comment]
https://github.com/smnorris/bcdata/issues/126

**Comment by NewGraphEnvironment** [comment]
looks like `ogr2ogr` converts the lowercase names in the `geojson`s to uppercase... annoying

**Comment by NewGraphEnvironment** [comment]
actually - the `-l` flag on good old `bcdata` worked fine. was a qlr issue (not in project directory when dragged in that caused the issue)
