### ISSUE TITLE
Ignore large files for field view to avoid memory issues on phones

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/dff-2022#72]
for now we will put uber large files in the `photos` directory as this is ignored on the phone by default.  We will likely want to change the name of that directory on future versions and tuck a `photos` directory inside

**Comment by NewGraphEnvironment** [comment]
can we use themes for this as well?

**Comment by Mateo9569** [comment]
As long as the large file in question is not selected in the layer view it won't cause any grief on the phone. Not sure what you're asking in regards to themes. As long as the available themes also do not include any large files when viewing on phone we should be ok.

**Comment by NewGraphEnvironment** [comment]
dealt with through `ignore_mobile` directory creation and `mergin-config.json`
