### ISSUE TITLE
QGIS crashes with latest lidar data

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/dff-2022#79]
Happened three times on March 17. QGIS program would just close suddenly without saving latest changes. 

PC device specifications
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	0272AFC3-7A3F-4A82-9ACA-415379289AE5
Product ID	00342-21995-77183-AAOEM
System type	64-bit operating system, x64-based processor

Lidar layers in viewer at time of crash:
![image](https://user-images.githubusercontent.com/99455166/226407013-6666a6d7-0223-4a43-bcd3-51a4f083a5df.png)

**Comment by NewGraphEnvironment** [comment]
Can you please provide a screenshot or print out of the size of that las file?

Then, could you please load the latest version of QGIS loaded and report the version number of what version of Q that is? 

Next, let’s test removing the physical las file from the project (can stay in the file for now though) and see if the crash still occurs. Really we willl likely never need the raw `las` as it is the products downstream we will use. Maybe that is it .

**Comment by Mateo9569** [comment]
The .las file is 623MB. I removed the physical file from the project. I updated my QGIS to version 3.30. My previous version was 3.24.3, maybe that was part of the problem. Since doing both of those things I haven't had any crashes. I will keep you posted here if I experience any further issues.
