### ISSUE TITLE
How to symbolize streams layer from `bcfishpass`  `.gpkg` dump 

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/dff-2022#83]
looks like latest `bcfishpass` `qlr` file uses views for linear habitat models but stream layer currently exported perhaps will not have enough detail for symbology?  Also, we need to be able to symbolize `bt_access` model (at a minimum - RB would likely be better as applicable in near all [study areas](https://github.com/NewGraphEnvironment/bcfishpass/blob/ng/parameters/newgraph/param_watersheds.csv)) to understand what is likely habitat using phone in the field.

https://bcfishpass.s3.us-west-2.amazonaws.com/freshwater_fish_habitat_accessibility_MODEL.gpkg.zip

```
$ ogrinfo freshwater_fish_habitat_accessibility_MODEL.gpkg
INFO: Open of `freshwater_fish_habitat_accessibility_MODEL.gpkg'
      using driver `GPKG' successful.
1: crossings (3D Measured Point)
2: gradient_barriers (3D Measured Point)
3: barriers_subsurfaceflow (3D Measured Point)
4: barriers_falls (3D Measured Point)
5: barriers_salmon (3D Measured Point)
6: barriers_steelhead (3D Measured Point)
7: model_access_salmon (3D Measured Line String)
8: model_access_steelhead (3D Measured Line String)
9: observations (3D Measured Point)
```

**Comment by smnorris** [comment]
Yes, the QGIS file depends on habitat modelling (discharge/CW based spawning/rearing) but current .gpkg export is just the access models for salmon and steelhead. The export contents are based on what the Province is willing to publish/support at this time, and not related to the QGIS file at all. Note also that publication in the DataBC catalogue is currently on hold, hopefully we will get a green light soon.

So to support field mapping, I can dump whatever we want to another file in the same spot.

Regarding BT and RB, how about a combined access model like this? 
https://github.com/smnorris/bcfishpass/blob/main/model/access/sql/model_access_ct_dv_rb.sql
Includes observations of BT/CT/DV/RB and uses 25% as the max gradient passable.

Another option recently discussed has been using observations of *all* species and a 25% threshold.

**Comment by NewGraphEnvironment** [comment]
we now have `mapping_code_sp`
